### PR TITLE
Add support for German and Norwegian

### PR DESCRIPTION
**Pull request by Syndesi**
Hi,

I added two stopword lists, one for German and one for Norwegian.
I'm not the author for the lists themselve but they are published under the MIT license and the source is mentioned in the files.

### CODE REVIEW

**Review by DavidBelicza — CHANGES_REQUESTED** [review]
Hi,

Thank you for the contribution. It is really cool. There is only one little thing what should be modified:

You can use your own real name or nick name and email as author in the PHPDoc @author tag.

**Review by DavidBelicza — APPROVED** [review]

**Comment by Syndesi** [comment]
Hi,

I changed the author tag to my name and replaced the email with my github profile. Furthermore I added stopword-lists for Spanish and French. I actually don't need these two languages myself, but I think they are used by so many people that they are worth including.
The organization actually has [more supported languages](https://github.com/stopwords-iso), but I wanted to ask you whether it is desirable to add these to this software or not :)
(Or if some languages could couse troubles, e.g. Chinese).

**Comment by Syndesi** [comment]
You are fast :D

**Comment by DavidBelicza** [comment]
Thanks for the update :) I create a new release soon.

**Comment by Syndesi** [comment]
Thats very cool :D 
I actually think that this project should get more attention because I haven't seen a library which is capable of keyword, highlight and summary extraction at the same time! :D

**Pull request merged**
